import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_ai/firebase_ai.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'package:taskhaura/home.dart';
import 'package:taskhaura/screens/mainscreen.dart';
import 'firebase_options.dart';   // generated by `flutterfire configure`

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
late final GenerativeModel gemini;   // global singleton

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  gemini = FirebaseAI.googleAI().generativeModel(model: 'gemini-2.5-flash');
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      title: 'Task Haura',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: const Color(0xFF74EC7A)),
      home: const MainScreen(), // <-- changed
    );
  }
}